quizzes/urls.py
from django.urls import path

from . import views

app_name = 'quizzes'
urlpatterns = [
  # ex: /quizzes/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /quizzes/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /quizzes/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /quizzes/5/vote/
    path('<int:quiz_id>/submit/', views.process_answers, name='process_answers'),
]

quizzical/urls.py
from django.contrib import admin
from django.urls import include, path

from rest_framework import routers

from quizzes import views

router = routers.DefaultRouter()
router.register(r'quizzes', views.QuizViewSet)

urlpatterns = [
    path('quizzes/', include('quizzes.urls')),
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

quizzes/models.py
import datetime
from django.db import models
from django.utils import timezone


class Quiz(models.Model):
    description = models.CharField(max_length=500)
    pub_date = models.DateTimeField("date published")

    def was_published_recently(self):
        now = timezone.now()
        # The pub_date should be between now and 1 day ago
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.description


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    quiz = models.ForeignKey(Quiz, models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    correct_choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

    def __str__(self):
        return "{} {}".format(
            self.question.question_text, self.correct_choice.choice_text
        )

quizzes/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from rest_framework import viewsets
from .serializers import QuizSerializer

from .models import Answer, Choice, Question, Quiz


class QuizViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows Quizzes to be viewed or edited.
    """
    queryset = Quiz.objects.all().order_by('-pub_date')
    serializer_class = QuizSerializer


class IndexView(generic.ListView):
    template_name = "quizzes/index.html"
    context_object_name = "latest_quiz_list"

    def get_queryset(self):
        """
        Return the last five published quizzes (not including those set to be
        published in the future).
        """
        return Quiz.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[
            :5
        ]


class DetailView(generic.DetailView):
    model = Quiz
    template_name = "quizzes/detail.html"

    def get_queryset(self):
        """
        Excludes any quizzes that aren't published yet.
        """
        return Quiz.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Quiz
    template_name = "quizzes/results.html"


def process_answers(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    questions = quiz.question_set.all()
    answers = {}

    try:
        for question in questions:
            selected_answer = request.POST["choice_{}".format(question.id)]
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the quiz form.
        return render(
            request,
            "quizzes/detail.html",
            {"quiz": quiz, "error_message": "You didn't answer all the questions"},
        )
    else:
        for question in questions:
            correct_answer = (
                "Correct"
                if Answer.objects.get(question=question).correct_choice.pk
                == int(request.POST["choice_{}".format(question.id)])
                else "Wrong"
            )
            answers[question] = correct_answer
        return render(
            request, "quizzes/results.html", {"quiz": quiz, "answers": answers}
        )

quizzes/templates/quizzes/detail.html
<h1>{{ quiz.description }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'quizzes:process_answers' quiz.id %}" method="post">
    {% csrf_token %}
    {% for question in quiz.question_set.all %}
        <p>{{question.question_text}}</p>
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice_{{ question.id }}" id="choice{{ choice.id }}" value="{{ choice.id }}">
            <label for="choice{{ choice.id }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    {% endfor %}
    <br>
    <input type="submit" value="Submit">
</form>

quizzes/templates/quizzes/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'quizzes/style.css' %}">

{% if latest_quiz_list %}
  <ul>
    {% for quiz in latest_quiz_list %}
        <li><a href="{% url 'quizzes:detail' quiz.id %}">{{ quiz.description }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <p>No quizzes are available.</p>
{% endif %}

quizzes/templates/quizzes/results.html
<h1>{{ quiz.description }}</h1>

<ul>
{% for question, result in answers.items %}
    <li>{{ question }} -- {{ result }}</li>
{% endfor %}
</ul>

<a href="{% url 'quizzes:detail' quiz.id %}">Take Quiz again?</a>